const $ = id => document.getElementById(id);
let datasets = [], selected = 'all', running = false;
const el = (tag, cls, text) => { const node = document.createElement(tag); if (cls) node.className = cls; if (text !== undefined) node.textContent = text; return node; };
const stamp = seconds => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
const filters = [['all', 'All content'], ['document', 'Documents'], ['image', 'Images'], ['audio', 'Audio'], ['video', 'Videos']];
const examples = { all: ['أرني فيديو عن مناسك الحج في مكة', 'أرني القبة الخضراء', 'Show me video of Makkah'], document: ['من يشرف على فهرسة المخطوطات؟', 'متى تفتح المكتبة أبوابها؟'], image: ['أرني صورة باب الملك عبد العزيز في مكة', 'صف ما يظهر في الصورة'], audio: ['كيف يعرّف التسجيل الطائرة؟', 'ما التحية المذكورة في التسجيل؟'], video: ['أرني فيديو عن مناسك الحج في مكة', 'ما الذي يشرحه فيديو منصة ويكي تعلم؟', 'أرني القبة الخضراء'] };
const evidenceLabels = { metadata: 'About this item', speech: 'Spoken evidence', frame: 'Text in video frame', visual_description: 'Visual scene description', text: 'Document passage', page: 'Scanned page' };
function anchorText(anchor) { if (anchor.kind === 'metadata') return 'Whole item'; if (anchor.page) return `Page ${anchor.page}`; if (anchor.start !== undefined) return anchor.end !== undefined ? `${stamp(anchor.start)} – ${stamp(anchor.end)}` : `${stamp(anchor.start)} scene`; return evidenceLabels[anchor.kind] || 'Source passage'; }
async function api(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data; }
function status(text, error = false) { $('status').textContent = text; $('status').className = error ? 'error' : ''; }
function setBusy(value) { running = value; document.querySelectorAll('button, textarea, select').forEach(node => node.disabled = value); $('ask-button').innerHTML = value ? 'Finding evidence…' : 'Find answers <span>→</span>'; }
function libraryRows(kind) { const rows = datasets.find(dataset => dataset.id === 'library')?.sources || []; return rows.filter(row => kind === 'all' || row.media_type === kind); }
function setQuestion(question) { $('question').value = question; $('question').focus(); }
function renderSuggestions() { const items = examples[selected] || examples.all; $('suggestions').replaceChildren(...items.map(question => { const button = el('button', '', question); button.type = 'button'; button.dir = 'auto'; button.onclick = () => setQuestion(question); return button; })); }
function choose(kind) { selected = kind; $('result').hidden = true; status(''); $('question').value = ''; renderCollections(); renderSuggestions(); $('evidence-title').textContent = kind === 'all' ? 'Explore the library' : `Explore ${filters.find(filter => filter[0] === kind)[1].toLowerCase()}`; $('evidence-help').textContent = 'Ask a question to receive an answer and the source material behind it.'; renderSources(libraryRows(kind)); }
function renderCollections() { $('collections').replaceChildren(...filters.map(([kind, label]) => { const button = el('button', `collection ${selected === kind ? 'active' : ''}`); button.setAttribute('aria-pressed', String(selected === kind)); const count = libraryRows(kind).length; button.append(el('span', 'collection-count', String(count)), el('strong', '', label), el('small', '', kind === 'all' ? 'Search across all sources' : `Explore ${label.toLowerCase()}`)); button.onclick = () => choose(kind); return button; })); }
function sourceType(row) { return evidenceLabels[row.evidence_type || row.anchor.kind] || 'Supporting source'; }
function appendMedia(card, row, passage) { if (['audio', 'video'].includes(row.media_type)) { const media = el(row.media_type); media.controls = true; media.preload = 'metadata'; media.src = `${row.media_url}#t=${row.anchor.start || 0}`; media.addEventListener('loadedmetadata', () => { media.currentTime = row.anchor.start || 0; }, { once: true }); card.append(media); if (row.matches?.length) { const moments = el('div', 'moments'); moments.append(el('span', 'moments-label', 'Explore matching moments')); for (const match of row.matches.flatMap(item => [item, ...(item.aligned || [])])) { const isMetadata = match.evidence_type === 'metadata'; const button = el('button', '', isMetadata ? 'About this item' : `${anchorText(match.anchor)} · ${evidenceLabels[match.evidence_type] || 'Evidence'}`); button.type = 'button'; button.onclick = () => { passage.textContent = match.original_text; if (!isMetadata) { media.currentTime = match.anchor.start || 0; media.play().catch(() => {}); } }; moments.append(button); } card.append(moments); } } else if (row.media_type === 'image') { const image = el('img', 'source-image'); image.src = row.media_url; image.alt = row.document; image.loading = 'lazy'; card.append(image); } }
function renderSources(rows) { $('source-count').textContent = `${rows.length} ${rows.length === 1 ? 'source' : 'sources'}`; $('sources').replaceChildren(...rows.map((row, index) => { const card = el('article', 'source-card'); card.id = `source-${row.id}`; const header = el('div', 'source-top'); const title = el('div'); title.append(el('div', 'source-kind', sourceType(row)), el('div', 'source-name', `${index + 1}. ${row.document}`)); header.append(title, el('span', 'anchor', anchorText(row.anchor))); card.append(header); const passage = el('p', 'passage', row.original_text); passage.dir = 'auto'; card.append(passage); appendMedia(card, row, passage); const meta = row.metadata || {}; const details = el('details', 'source-details'); details.append(el('summary', '', 'Source information')); const info = [meta.author, meta.source_url ? 'Original source available' : null, meta.original_start_seconds ? `Clip begins at ${stamp(meta.original_start_seconds)} in the original recording` : null].filter(Boolean).join(' · '); if (info) details.append(el('p', '', info)); card.append(details); return card; })); }
function renderAnswer(result) { const box = $('result'); box.replaceChildren(); box.hidden = false; const header = el('div', 'answer-header'); const title = el('div'); title.append(el('p', 'eyebrow', 'ANSWER'), el('h2', '', result.generation === 'insufficient_evidence' ? 'What the sources show' : 'Answer based on your sources')); header.append(title, el('span', 'answer-badge', result.generation === 'grounded' ? 'Source-backed' : 'Matching sources')); box.append(header); const answer = el('div', 'answer-text', result.answer); answer.dir = 'auto'; box.append(answer); for (const citation of result.citations || []) { const row = result.sources.find(source => source.id === (citation.source_id || citation.id)); const citationBox = el('div', 'citation'); citationBox.append(el('div', 'citation-label', `${citation.evidence_type === 'visual_description' ? 'Visual scene description' : citation.evidence_type === 'speech' ? 'Spoken evidence' : 'Supporting evidence'}${citation.anchor ? ` · ${anchorText(citation.anchor)}` : ''}`)); const quote = el('blockquote', '', citation.quote); quote.dir = 'auto'; citationBox.append(quote); if (row) { const button = el('button', '', `Open ${row.document} at this evidence`); button.onclick = () => { const source = $(`source-${row.id}`); source.scrollIntoView({ behavior: 'smooth', block: 'center' }); const media = source.querySelector('video,audio'); if (media && citation.anchor?.start !== undefined) media.currentTime = citation.anchor.start; source.classList.add('highlight'); setTimeout(() => source.classList.remove('highlight'), 2000); }; citationBox.append(button); } box.append(citationBox); } const note = el('p', 'answer-note', result.citations?.length ? 'Open the evidence below to review the original passage or media moment.' : 'Review the matching sources below.'); box.append(note); $('evidence-title').textContent = 'Supporting sources'; $('evidence-help').textContent = 'These are the passages, scenes and moments used to find the answer.'; renderSources(result.sources || []); box.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
$('ask-form').onsubmit = async event => { event.preventDefault(); const question = $('question').value.trim(); if (!question || running) return; setBusy(true); $('result').hidden = true; status('Finding the most relevant source material…'); try { const job = await api('/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dataset: 'library', question, media_type: selected }) }); let finished = false; for (let attempt = 0; attempt < 270; attempt += 1) { await new Promise(resolve => setTimeout(resolve, 2000)); const progress = await api(`/api/jobs/${job.job_id}`); if (progress.status === 'error') throw new Error(progress.error); if (progress.status === 'done') { renderAnswer(progress.result); status('Your answer and supporting evidence are ready.'); finished = true; break; } } if (!finished) throw new Error('This is taking longer than expected. Please try again.'); } catch (error) { status(error.message, true); } finally { setBusy(false); } };
document.querySelectorAll('[data-prompt]').forEach(button => button.onclick = () => { choose(button.dataset.kind || 'all'); setQuestion(button.dataset.prompt); });
api('/api/catalog').then(data => {
	datasets = data.datasets;
	choose('all');
	const total = datasets.reduce((sum, dataset) => sum + dataset.count, 0);
	if ($('workspace-count')) $('workspace-count').textContent = `${total} INDEXED ITEMS`;
}).catch(error => status(`Could not load the library. ${error.message}`, true));

document.querySelectorAll('[data-scroll]').forEach(button => button.onclick = () => {
	document.getElementById(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
	document.querySelectorAll('.rail-link').forEach(item => item.classList.toggle('active', item === button));
	$('app-rail')?.classList.remove('open');
});
$('menu-toggle')?.addEventListener('click', () => $('app-rail').classList.toggle('open'));
$('clear-search')?.addEventListener('click', () => { $('question').value = ''; $('result').hidden = true; status(''); $('question').focus(); });
$('focus-evidence')?.addEventListener('click', () => $('evidence').scrollIntoView({ behavior: 'smooth', block: 'start' }));
