const $ = id => document.getElementById(id);
let datasets = [], selected = 'text', running = false;
const el = (tag, cls, text) => { const node = document.createElement(tag); if(cls) node.className=cls; if(text !== undefined) node.textContent=text; return node; };
const stamp = seconds => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
function anchorText(a) { if(a.kind==='metadata')return 'Whole video'; if(a.page) return `Page ${a.page}`; if(a.start !== undefined) return a.end !== undefined ? `${stamp(a.start)}–${stamp(a.end)}` : `${stamp(a.start)} frame`; return a.kind==='visual_description'?'Image description':'Text passage'; }
async function api(url, options) { const response=await fetch(url,options); const data=await response.json(); if(!response.ok) throw new Error(data.error || 'Request failed.'); return data; }
function status(text,error=false) { $('status').textContent=text; $('status').className=error?'error':''; }
function setBusy(value) { running=value; document.querySelectorAll('button,textarea,select').forEach(n=>n.disabled=value); $('ask-button').textContent=value?'Finding evidence…':'Search library ↗'; }
const filters=[['all','All'],['document','Documents'],['image','Images'],['audio','Audio'],['video','Videos']];
function libraryRows(kind) { const rows=datasets.find(d=>d.id==='library')?.sources||[];return rows.filter(r=>kind==='all'||r.media_type===kind); }
function choose(kind) { selected=kind;$('media-filter').hidden=true;$('result').hidden=true;status('');$('question').value='';renderCollections();const questions=kind==='audio'?['كيف يعرّف التسجيل الطائرة؟']:kind==='document'?['من يشرف على فهرسة المخطوطات؟']:['Show me video of Makkah','أرني القبة الخضراء'];$('suggestions').replaceChildren(...questions.map(q=>{const b=el('button','',q);b.type='button';b.dir='auto';b.onclick=()=>{$('question').value=q;$('question').focus();};return b;}));$('evidence-title').textContent='Library';$('evidence-help').textContent='Each source appears once. Search to find matching passages and timestamps.';renderSources(libraryRows(kind)); }
function renderCollections() { $('collections').replaceChildren(...filters.map(([kind,label])=>{const b=el('button',`collection ${selected===kind?'active':''}`);b.setAttribute('aria-pressed',String(selected===kind));b.disabled=running;const count=libraryRows(kind).length;const plural=kind==='all'?'sources':label.toLowerCase();const unit=count===1&&plural.endsWith('s')?plural.slice(0,-1):plural;b.append(el('span','count',`${count} ${unit}`),el('strong','',label));b.onclick=()=>choose(kind);return b;})); }
function renderSources(rows) { $('source-count').textContent=`${rows.length} sources`; $('sources').replaceChildren(...rows.map((row,index)=>{const card=el('article','source-card');card.id=`source-${row.id}`;const top=el('div','source-top'), title=el('div');title.append(el('div','source-kind',row.anchor.kind.replaceAll('_',' ')),el('div','source-name',`${index+1}. ${row.document}`));top.append(title,el('span','anchor',anchorText(row.anchor)));card.append(top);if(row.source_label){card.append(el('p','source-meta','Source label (whole asset): '+row.source_label));}if(row.similarity!==undefined){card.append(el('p','source-meta','Candidate similarity: '+row.similarity+' · not a confidence score'));}const text=el('p','passage',row.original_text);text.dir='auto';if(row.original_text.length>420){const details=el('details');details.append(el('summary','', 'Read original extracted passage'),text);card.append(details);}else card.append(text);
if(['audio','video'].includes(row.media_type)){const media=el(row.media_type);media.controls=true;media.preload='none';media.src=row.media_url+`#t=${row.anchor.start||0}`;const seek=()=>{media.currentTime=row.anchor.start||0;};media.addEventListener('loadedmetadata',seek,{once:true});card.append(media);if(row.matches){const list=el('div','suggestions');for(const match of row.matches.flatMap(m=>[m,...(m.aligned||[])])){const isMetadata=match.evidence_type==='metadata';const button=el('button','',isMetadata?'Source label · whole video':`${match.relation ? match.relation+" · " : ""}${match.evidence_type} · ${anchorText(match.anchor)}`);button.type='button';button.onclick=()=>{text.textContent=match.original_text;text.closest('details')?.setAttribute('open','');if(!isMetadata){media.currentTime=match.anchor.start||0;media.play().catch(()=>{});}};list.append(button);}card.append(list);}}else if(row.media_type==='image'){const img=el('img','source-image');img.src=row.media_url;img.alt=row.document;img.loading='lazy';card.append(img);}else {const link=el('a','','Open original source ↗');link.href=row.media_url;link.target='_blank';link.rel='noopener';card.append(link);}
const meta=row.metadata||{};for(const [label,url] of [['Source & attribution',meta.source_url],['License',meta.license_url]]){if(typeof url==='string' && /^https?:\/\//.test(url)){const link=el('a','source-meta',label+' ↗');link.href=url;link.target='_blank';link.rel='noopener';card.append(link,document.createTextNode(' · '));}}card.append(el('div','source-meta',[row.engine,meta.author,meta.original_start_seconds?`Clip begins at ${stamp(meta.original_start_seconds)} in original recording`:null].filter(Boolean).join(' · ')));return card;})); }
function renderAnswer(result,elapsed) { const box=$('result');box.replaceChildren();box.hidden=false;const header=el('div','result-header');header.append(el('h2','','Answer'),el('span',`tag ${result.mode==='saved'?'saved-tag':''}`,result.mode==='saved'?'Recorded test · known quality failures':`Live response${elapsed?` · ${elapsed}s`:''}`));box.append(header); const answer=el('div','answer-text',result.answer);answer.dir='auto';box.append(answer);
(result.citations||[]).forEach((citation,index)=>{const row=result.sources.find(s=>s.id===citation.id);const block=el('div','citation');block.append(el('div','source-kind',`Citation ${index+1}${row?' · '+anchorText(row.anchor):''}`));const quote=el('blockquote','',citation.quote);quote.dir='auto';block.append(quote);if(row){const button=el('button','',`View ${row.document} ↓`);button.onclick=()=>{const source=$(`source-${row.id}`);source.scrollIntoView({behavior:'smooth',block:'center'});source.classList.add('highlight');setTimeout(()=>source.classList.remove('highlight'),2500);};block.append(button);}box.append(block);});
if(result.retrieval==='visual_candidates'||result.retrieval==='video_candidates'||result.retrieval==='library_candidates'){const note=el('p','result-foot','Candidate matches, not verified identities. Speech, OCR and generated descriptions can contain errors. Source labels apply to the whole video. Select an evidence button to inspect its text and timestamp.');box.append(note);$('evidence-title').textContent=result.retrieval==='video_candidates'?'Matching videos':'Matching sources';$('evidence-help').textContent='Review each candidate. A similar scene may depict a different place.';renderSources(result.sources||[]);return;}
const foot=el('div','result-foot');foot.append(el('strong','',(result.citations||[]).length?'Quote text checked. ':'No validated citations. '),document.createTextNode('This does not verify every claim. Compare the answer with the original passage or recording.'));box.append(foot);$('evidence-title').textContent='Retrieved evidence';$('evidence-help').textContent='Original extracted passages used for this response. Recognition errors may remain.';renderSources(result.sources||[]);box.scrollIntoView({behavior:'smooth',block:'start'}); }
$('ask-form').onsubmit=async event=>{event.preventDefault();const question=$('question').value.trim();if(!question||running)return;const dataset='library';setBusy(true);$('result').hidden=true;status('Searching the selected media type for matching sources and evidence.');try{const job=await api('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset,question,media_type:selected})});let completed=false;for(let i=0;i<270;i++){await new Promise(resolve=>setTimeout(resolve,2000));const progress=await api(`/api/jobs/${job.job_id}`);if(progress.status==='error')throw new Error(progress.error);if(progress.status==='done'){renderAnswer(progress.result,progress.elapsed);status('Response ready. Review the supporting evidence below.');completed=true;break;}}if(!completed)throw new Error('The request is taking too long. Check the server terminal before trying again.');}catch(error){status(error.message,true);}finally{setBusy(false);}};
document.querySelectorAll('[data-example]').forEach(button=>button.onclick=async()=>{if(running)return;choose('all');setBusy(true);try{const name=button.dataset.example;$('question').value=datasets.find(d=>d.id==='media').questions[name==='audio'?0:1];renderAnswer(await api(`/api/examples/${name}`));status('Recorded test output loaded. This example includes known answer-quality failures.');}catch(error){status(error.message,true);}finally{setBusy(false);}});
api('/api/catalog').then(data=>{datasets=data.datasets;choose('all');}).catch(error=>status('Could not load local collections. '+error.message,true));
